### ISSUE TITLE
error_display function 

### ISSUE THREAD

**Issue by taono** [inno-code/simplephp#10]
I used ini_set( 'error_display", 1); & error_reporting ( E-ALL | E-STRICT); to enable php error report. It doesn't work. Then I tried to enable error report through editing php.ini file, but I couldn't find it. Ullman's book chapter 3 & appendix A: installation and configuration has a section about PHP configuration but it's not clear  (can't find php.ini. file). Help is needed to enable error report. Thanks!

**Comment by zoelogic** [comment]
### How to find php.ini file
- Make the phpinfo.php script from Ullmans book. I forget what chapter it is in. 
  But, using the php documentation below will give you the same solution.
  Code below is from the [php documentation](http://php.net/manual/en/function.phpinfo.php)

``` php
<?php

// Option1: Show all information, defaults to INFO_ALL
phpinfo();


// Option2: Shows The configuration line, php.ini location, build date, 
// Web Server, System and more.
phpinfo(INFO_GENERAL);

?>
```
- Run the above script and look for the ouput that shows where the php.ini file is. 
  When running the above choose option1 or 2 do not run both.
- Note: The php.ini is where all your custom configuration of PHP on your machine goes. 
  So, we need to get used to using and modifying this file. 
- Configure php.ini file to do error reporting according to how the books says to set it.

**Comment by zoelogic** [comment]
<b>Todo</b> Let's add a `phpinfo.php` script to the simplephp project. 
This will allow us to conveniently run the script and see our php configs as needed. 
Put in: `/simplephp/skeleton`

**Comment by zoe-1** [comment]
Where is everyone?  Have you guys stopped meeting?

**Comment by taono** [comment]
I have been traveling @zoe-1, and there is generally no internet access for me. our meeting will resume next week.
