### ISSUE TITLE
Installation and Config Guide

### ISSUE THREAD

**Issue by taono** [inno-code/simplephp#11]
LAMP Installation Complete guide:
 https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu

**Comment by taono** [comment]
Git Repo Command line: 
https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository

**Comment by taono** [comment]
Komodo Installation: 

http://ubuntuhandbook.org/index.php/2014/04/install-komodo-edit-8-in-ubuntu-14-04/

After download of komodo go into Komodo application directory and run below command.
Ensure ./install.sh is in this directory before executing command.

sudo ./install.sh

**Comment by zoelogic** [comment]
Let's move this content into a ./guides directory. 
See #13 for details about setting this up.

**Comment by taono** [comment]
## Git [Documentation](https://git-scm.com/doc)
