### ISSUE TITLE
can't install komodo. multiple methods attempted

### ISSUE THREAD

**Issue by natkre** [inno-code/simplephp#12]
here's my command line history, please let me know what went wrong and how to fix @zoelogic @taono @papanja

nathanael@nathanael-Inspiron-3551:~$ ./install.sh
bash: ./install.sh: No such file or directory
nathanael@nathanael-Inspiron-3551:~$ pwd
/home/nathanael
nathanael@nathanael-Inspiron-3551:~$ cd /
nathanael@nathanael-Inspiron-3551:/$ ls
bin    dev   initrd.img  lib64       mnt   root  srv  usr
boot   etc   lib         lost+found  opt   run   sys  var
cdrom  home  lib32       media       proc  sbin  tmp  vmlinuz
nathanael@nathanael-Inspiron-3551:/$ cd bin
nathanael@nathanael-Inspiron-3551:/bin$ ls
bash                  fgconsole   nc                       setfacl
bunzip2               fgrep       nc.openbsd               setfont
busybox               findmnt     netcat                   setupcon
bzcat                 fuser       netstat                  sh
bzcmp                 fusermount  nisdomainname            sh.distrib
bzdiff                getfacl     ntfs-3g                  sleep
bzegrep               grep        ntfs-3g.probe            ss
bzexe                 gunzip      ntfs-3g.secaudit         static-sh
bzfgrep               gzexe       ntfs-3g.usermap          stty
bzgrep                gzip        ntfscat                  su
bzip2                 hostname    ntfsck                   sync
bzip2recover          ip          ntfscluster              tailf
bzless                kbd_mode    ntfscmp                  tar
bzmore                keyctl      ntfsdump_logfile         tempfile
cat                   kill        ntfsfix                  touch
chacl                 kmod        ntfsinfo                 true
chgrp                 less        ntfsls                   udevadm
chmod                 lessecho    ntfsmftalloc             ulockmgr_server
chown                 lessfile    ntfsmove                 umount
chvt                  lesskey     ntfstruncate             uname
cp                    lesspipe    ntfswipe                 uncompress
cpio                  ln          open                     unicode_start
dash                  loadkeys    openvt                   vdir
date                  login       pidof                    vmmouse_detect
dbus-cleanup-sockets  loginctl    ping                     which
dbus-daemon           lowntfs-3g  ping6                    whiptail
dbus-uuidgen          ls          plymouth                 ypdomainname
dd                    lsblk       plymouth-upstart-bridge  zcat
df                    lsmod       ps                       zcmp
dir                   mkdir       pwd                      zdiff
dmesg                 mknod       rbash                    zegrep
dnsdomainname         mktemp      readlink                 zfgrep
domainname            more        red                      zforce
dumpkeys              mount       rm                       zgrep
echo                  mountpoint  rmdir                    zless
ed                    mt          rnano                    zmore
efibootmgr            mt-gnu      running-in-container     znew
egrep                 mv          run-parts
false                 nano        sed
nathanael@nathanael-Inspiron-3551:/bin$ cd sh
bash: cd: sh: Not a directory
nathanael@nathanael-Inspiron-3551:/bin$ ls
bash                  fgconsole   nc                       setfacl
bunzip2               fgrep       nc.openbsd               setfont
busybox               findmnt     netcat                   setupcon
bzcat                 fuser       netstat                  sh
bzcmp                 fusermount  nisdomainname            sh.distrib
bzdiff                getfacl     ntfs-3g                  sleep
bzegrep               grep        ntfs-3g.probe            ss
bzexe                 gunzip      ntfs-3g.secaudit         static-sh
bzfgrep               gzexe       ntfs-3g.usermap          stty
bzgrep                gzip        ntfscat                  su
bzip2                 hostname    ntfsck                   sync
bzip2recover          ip          ntfscluster              tailf
bzless                kbd_mode    ntfscmp                  tar
bzmore                keyctl      ntfsdump_logfile         tempfile
cat                   kill        ntfsfix                  touch
chacl                 kmod        ntfsinfo                 true
chgrp                 less        ntfsls                   udevadm
chmod                 lessecho    ntfsmftalloc             ulockmgr_server
chown                 lessfile    ntfsmove                 umount
chvt                  lesskey     ntfstruncate             uname
cp                    lesspipe    ntfswipe                 uncompress
cpio                  ln          open                     unicode_start
dash                  loadkeys    openvt                   vdir
date                  login       pidof                    vmmouse_detect
dbus-cleanup-sockets  loginctl    ping                     which
dbus-daemon           lowntfs-3g  ping6                    whiptail
dbus-uuidgen          ls          plymouth                 ypdomainname
dd                    lsblk       plymouth-upstart-bridge  zcat
df                    lsmod       ps                       zcmp
dir                   mkdir       pwd                      zdiff
dmesg                 mknod       rbash                    zegrep
dnsdomainname         mktemp      readlink                 zfgrep
domainname            more        red                      zforce
dumpkeys              mount       rm                       zgrep
echo                  mountpoint  rmdir                    zless
ed                    mt          rnano                    zmore
efibootmgr            mt-gnu      running-in-container     znew
egrep                 mv          run-parts
false                 nano        sed
nathanael@nathanael-Inspiron-3551:/bin$ cd sh
bash: cd: sh: Not a directory
nathanael@nathanael-Inspiron-3551:/bin$ cd sh
bash: cd: sh: Not a directory
nathanael@nathanael-Inspiron-3551:/bin$ cd /sh
bash: cd: /sh: No such file or directory
nathanael@nathanael-Inspiron-3551:/bin$ pwd
/bin
nathanael@nathanael-Inspiron-3551:/bin$ ls
bash                  fgconsole   nc                       setfacl
bunzip2               fgrep       nc.openbsd               setfont
busybox               findmnt     netcat                   setupcon
bzcat                 fuser       netstat                  sh
bzcmp                 fusermount  nisdomainname            sh.distrib
bzdiff                getfacl     ntfs-3g                  sleep
bzegrep               grep        ntfs-3g.probe            ss
bzexe                 gunzip      ntfs-3g.secaudit         static-sh
bzfgrep               gzexe       ntfs-3g.usermap          stty
bzgrep                gzip        ntfscat                  su
bzip2                 hostname    ntfsck                   sync
bzip2recover          ip          ntfscluster              tailf
bzless                kbd_mode    ntfscmp                  tar
bzmore                keyctl      ntfsdump_logfile         tempfile
cat                   kill        ntfsfix                  touch
chacl                 kmod        ntfsinfo                 true
chgrp                 less        ntfsls                   udevadm
chmod                 lessecho    ntfsmftalloc             ulockmgr_server
chown                 lessfile    ntfsmove                 umount
chvt                  lesskey     ntfstruncate             uname
cp                    lesspipe    ntfswipe                 uncompress
cpio                  ln          open                     unicode_start
dash                  loadkeys    openvt                   vdir
date                  login       pidof                    vmmouse_detect
dbus-cleanup-sockets  loginctl    ping                     which
dbus-daemon           lowntfs-3g  ping6                    whiptail
dbus-uuidgen          ls          plymouth                 ypdomainname
dd                    lsblk       plymouth-upstart-bridge  zcat
df                    lsmod       ps                       zcmp
dir                   mkdir       pwd                      zdiff
dmesg                 mknod       rbash                    zegrep
dnsdomainname         mktemp      readlink                 zfgrep
domainname            more        red                      zforce
dumpkeys              mount       rm                       zgrep
echo                  mountpoint  rmdir                    zless
ed                    mt          rnano                    zmore
efibootmgr            mt-gnu      running-in-container     znew
egrep                 mv          run-parts
false                 nano        sed
nathanael@nathanael-Inspiron-3551:/bin$ cd ..
nathanael@nathanael-Inspiron-3551:/$ ls
bin    dev   initrd.img  lib64       mnt   root  srv  usr
boot   etc   lib         lost+found  opt   run   sys  var
cdrom  home  lib32       media       proc  sbin  tmp  vmlinuz
nathanael@nathanael-Inspiron-3551:/$ cd /bin/sh
bash: cd: /bin/sh: Not a directory
nathanael@nathanael-Inspiron-3551:/$ ./install.sh
bash: ./install.sh: No such file or directory
nathanael@nathanael-Inspiron-3551:/$ ./install.sh -h
bash: ./install.sh: No such file or directory
nathanael@nathanael-Inspiron-3551:/$ cd bin
nathanael@nathanael-Inspiron-3551:/bin$ l
bash\*                  fgconsole\*   nc@                       setfacl*
bunzip2\*               fgrep\*       nc.openbsd\*               setfont*
busybox\*               findmnt\*     netcat@                   setupcon*
bzcat\*                 fuser\*       netstat\*                  sh@
bzcmp@                 fusermount\*  nisdomainname@            sh.distrib@
bzdiff\*                getfacl\*     ntfs-3g\*                  sleep*
bzegrep@               grep\*        ntfs-3g.probe\*            ss*
bzexe\*                 gunzip\*      ntfs-3g.secaudit\*         static-sh@
bzfgrep@               gzexe\*       ntfs-3g.usermap\*          stty*
bzgrep\*                gzip\*        ntfscat\*                  su*
bzip2\*                 hostname\*    ntfsck\*                   sync*
bzip2recover\*          ip\*          ntfscluster\*              tailf*
bzless@                kbd_mode\*    ntfscmp\*                  tar*
bzmore\*                keyctl\*      ntfsdump_logfile\*         tempfile*
cat\*                   kill\*        ntfsfix\*                  touch*
chacl\*                 kmod\*        ntfsinfo\*                 true*
chgrp\*                 less\*        ntfsls\*                   udevadm*
chmod\*                 lessecho\*    ntfsmftalloc\*             ulockmgr_server*
chown\*                 lessfile@    ntfsmove\*                 umount*
chvt\*                  lesskey\*     ntfstruncate\*             uname*
cp\*                    lesspipe\*    ntfswipe\*                 uncompress*
cpio\*                  ln\*          open@                     unicode_start*
dash\*                  loadkeys\*    openvt\*                   vdir*
date\*                  login\*       pidof@                    vmmouse_detect*
dbus-cleanup-sockets\*  loginctl\*    ping\*                     which*
dbus-daemon\*           lowntfs-3g\*  ping6\*                    whiptail*
dbus-uuidgen\*          ls\*          plymouth\*                 ypdomainname@
dd\*                    lsblk\*       plymouth-upstart-bridge\*  zcat*
df\*                    lsmod@       ps\*                       zcmp*
dir\*                   mkdir\*       pwd\*                      zdiff*
dmesg\*                 mknod\*       rbash@                    zegrep*
dnsdomainname@         mktemp\*      readlink\*                 zfgrep*
domainname@            more\*        red\*                      zforce*
dumpkeys\*              mount\*       rm\*                       zgrep*
echo\*                  mountpoint\*  rmdir\*                    zless*
ed\*                    mt@          rnano@                    zmore*
efibootmgr\*            mt-gnu\*      running-in-container\*     znew*
egrep\*                 mv\*          run-parts*
false\*                 nano\*        sed*
nathanael@nathanael-Inspiron-3551:/bin$ cd ..
nathanael@nathanael-Inspiron-3551:/$ pwd
/
nathanael@nathanael-Inspiron-3551:/$ ls
bin    dev   initrd.img  lib64       mnt   root  srv  usr
boot   etc   lib         lost+found  opt   run   sys  var
cdrom  home  lib32       media       proc  sbin  tmp  vmlinuz
nathanael@nathanael-Inspiron-3551:/$ cs tmp
The program 'cs' is currently not installed. You can install it by typing:
sudo apt-get install csound
nathanael@nathanael-Inspiron-3551:/$ cd tmp
nathanael@nathanael-Inspiron-3551:/tmp$ ls
ssh-q5UnLLM1Zf7o  unity_support_test.0
nathanael@nathanael-Inspiron-3551:/tmp$ mkdir sh
nathanael@nathanael-Inspiron-3551:/tmp$ pwd
/tmp
nathanael@nathanael-Inspiron-3551:/tmp$ ls
sh  ssh-q5UnLLM1Zf7o  unity_support_test.0
nathanael@nathanael-Inspiron-3551:/tmp$ ./install.sh
bash: ./install.sh: No such file or directory
nathanael@nathanael-Inspiron-3551:/tmp$ ./ install.sh
bash: ./: Is a directory
nathanael@nathanael-Inspiron-3551:/tmp$ pwd
/tmp
nathanael@nathanael-Inspiron-3551:/tmp$ ls
sh  ssh-q5UnLLM1Zf7o  unity_support_test.0
nathanael@nathanael-Inspiron-3551:/tmp$ cd sh
nathanael@nathanael-Inspiron-3551:/tmp/sh$ pwd
/tmp/sh
nathanael@nathanael-Inspiron-3551:/tmp/sh$ ./install.sh
bash: ./install.sh: No such file or directory
nathanael@nathanael-Inspiron-3551:/tmp/sh$ sudo ./install.sh
[sudo] password for nathanael: 
sudo: ./install.sh: command not found
nathanael@nathanael-Inspiron-3551:/tmp/sh$ sudo add-apt-repositary ppa:mystic-mirage/komodo-edit
sudo: add-apt-repositary: command not found
nathanael@nathanael-Inspiron-3551:/tmp/sh$ ^C
nathanael@nathanael-Inspiron-3551:/tmp/sh$ ^C
nathanael@nathanael-Inspiron-3551:/tmp/sh$

**Comment by zoelogic** [comment]
@natkre Good to see you are getting started :-)

Your problem is described below:
1.) You download Komodo from the web.
This will create a directory with the Komodo application code inside it.
When you download the application the installer will ask you where to put this directory.
I believe @taono put this in a directory we made called thirdparty.  This is where we save third party
tools like Komodo.  
`~/Workspace/Thirdparty`
or something like the above. This is our style preference, but in reality you can put it wherever you want.  
2.)   Most importantly, you need to remember where you put the Komodo application directory after you download it because you need to enter that directory and run the command `./install.sh`
This script will install Komodo for you.  But you must be in the root directory of the Komodo app, otherwise, the command `./install.sh` script is not there to execute.  This is your current problem, you are in `/home/nathanael/` and execute `./install.sh` but there is not `./install.sh` script in that directory.
Example solution:
- Download Komodo to `~/Workspace/Thirdparty`
- This creates the directory `~/Workspace/Thirdparty/Komodo`
- move into Komodo root: `cd  ~/Worskpace/Thirdparty/Komodo`
  This is the step you skipped.
- `ls`  and you should see a file named: `./install.sh`
- `./install.sh` execute the install script and Komodo gets installed.

**Comment by zoelogic** [comment]
@natkre 
Please reply to people who answer your post questions.
