### ISSUE TITLE
./guides created, how to show on inno-code/simplephp?

### ISSUE THREAD

**Issue by taono** [inno-code/simplephp#15]
### Two Questions
1. now I have created guides folder on `taono/simplephp` , what shall I do next to make it shown on `inno-code/simplephp?`
2. I have deleted experiment folder from locally and push the changes to git, why is it still there on my forked directory simplephp?

**Comment by zoelogic** [comment]
You want to push your changes to the forked directory. 
If your PR is merged into master than your PR becomes the latest commit of the master branch of 
inno-code/simplephp. First changes go into the PR then when the PR is ready the changes are 
merged into master.  When we have a PR satisfying the requirements then we will merge it in.

**Comment by taono** [comment]
@zoelogic any new assignment?
