### ISSUE TITLE
Created inno-code gitter chatroom. 

### ISSUE THREAD

**Issue by zoelogic** [inno-code/simplephp#16]
Created a inno-code chatroom to encourage online discussion. 
Check it out :-)
Public: https://gitter.im/inno-code/simplephp
Owners: https://gitter.im/inno-code

**Comment by toby-1-kenobi** [comment]
Hi, can only inno-code members use that chatroom? How do I become a member?

**Comment by zoelogic** [comment]
Hi Toby,
Good to have you participating.
We will make another chatroom open to all.  Github restricts organization chatrooms to owners. 
explanation [here](https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-rooms)

**Comment by zoelogic** [comment]
Just started a public chatroom named after the repo inside inno-code.
[simplephp](https://gitter.im/inno-code/simplephp)

**Comment by taono** [comment]
thanks for creating the chatroom zoelogic. I'm looking forward to your return!
