### ISSUE TITLE
Questions and comments.

### ISSUE THREAD

**Issue by taono** [inno-code/simplephp#9]
Please feel free to post your questions or comments here.

**Comment by taono** [comment]
@zoelogic I have submitted all assignments. Please let me know if you can't see them. Feel free to add new assignments. I'll help @papanja and @natkre keep up. Thanks.

**Comment by taono** [comment]
flashcards that serve as complementary material to your Ullman book: 
http://www.cram.com/flashcards/php-3552889

@natkre & @papanja

**Comment by zoelogic** [comment]
@taono nice work with the flashcards. 
In respect to questions and comments, that is what creating issues are for. If someone has a problem or 
question they create an issue.  The community provides a solution then the issue is closed and we move on.
